version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/playwright
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: /packages/ai
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: /packages/insights
    schedule: { interval: weekly }
  - package-ecosystem: bundler
    directory: /packages/ruby
    schedule: { interval: weekly }
  - package-ecosystem: maven
    directory: /packages/api-java
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
