import { redactText } from './redaction.js';
import type { DiagnosticContext, EvidenceBuffer, LocatorTelemetry, PageLike, RedactionPolicy, SdetFlowPlaywrightConfig, TestInfoLike } from './types.js';
export interface DiagnosticInput { page?:PageLike; testInfo?:TestInfoLike; error?:unknown; evidence?:Partial<EvidenceBuffer>; }
export interface CaptureResult { context:DiagnosticContext; metadataAttached:boolean; screenshotAttached:boolean; domAttached:boolean; warnings:string[]; }
const err=(e:unknown)=>e===undefined?undefined:e instanceof Error?`${e.name}: ${e.message}`:String(e);
async function title(page?:PageLike){if(!page?.title)return undefined;try{return await page.title()}catch{return undefined}}
function cap(items:string[]|undefined,max:number,redaction:Partial<RedactionPolicy>):string[]|undefined{if(!items?.length)return undefined;return items.slice(-max).map(x=>redactText(x,redaction))}
export async function buildDiagnosticContext(input:DiagnosticInput,redaction:Partial<RedactionPolicy>={},includeDom=false,maxDomChars=200000,maxLogEntries=200):Promise<DiagnosticContext>{
 const t=await title(input.page),u=input.page?.url?.();let dom:string|undefined;if(includeDom&&input.page?.content){try{dom=redactText((await input.page.content()).slice(0,maxDomChars),redaction)}catch{}}
 const locatorTelemetry:LocatorTelemetry[]|undefined=input.evidence?.locators?.slice(-maxLogEntries).map(e=>({...e,attempts:e.attempts.map(a=>({...a,...(a.error?{error:redactText(a.error,redaction)}:{})}))}));
 const consoleEntries=cap(input.evidence?.console,maxLogEntries,redaction); const networkEntries=cap(input.evidence?.network,maxLogEntries,redaction);
 return {schemaVersion:'1.1',test:{...(input.testInfo?.title===undefined?{}:{title:redactText(input.testInfo.title,redaction)}),...(input.testInfo?.status===undefined?{}:{status:input.testInfo.status}),...(input.testInfo?.expectedStatus===undefined?{}:{expectedStatus:input.testInfo.expectedStatus}),...(input.testInfo?.retry===undefined?{}:{retry:input.testInfo.retry}),...(input.testInfo?.duration===undefined?{}:{durationMs:input.testInfo.duration}),...(input.testInfo?.project?.name===undefined?{}:{project:redactText(input.testInfo.project.name,redaction)})},page:{...(u===undefined?{}:{url:redactText(u,redaction)}),...(t===undefined?{}:{title:redactText(t,redaction)})},...(err(input.error)===undefined?{}:{error:redactText(err(input.error)!,redaction)}),...(dom===undefined?{}:{dom}),...(consoleEntries===undefined?{}:{console:consoleEntries}),...(networkEntries===undefined?{}:{network:networkEntries}),...(locatorTelemetry?.length?{locatorTelemetry}:{}),capturedAt:new Date().toISOString(),redactionApplied:true};
}
export async function captureFailureDiagnostics(input:DiagnosticInput,config:Readonly<SdetFlowPlaywrightConfig>):Promise<CaptureResult>{const warnings:string[]=[];const context=await buildDiagnosticContext(input,config.redaction,config.artifacts.includeDom,config.artifacts.maxDomChars,config.artifacts.maxLogEntries);const attach=input.testInfo?.attach?.bind(input.testInfo);let metadataAttached=false,screenshotAttached=false,domAttached=false;if(config.artifacts.attachMetadata&&attach)try{await attach('sdetflow-diagnostic.json',{body:JSON.stringify(context,null,2),contentType:'application/json'});metadataAttached=true}catch(e){warnings.push(`metadata attachment failed: ${err(e)??'unknown error'}`)}if(config.artifacts.screenshotOnFailure&&attach&&input.page?.screenshot)try{const bytes=await input.page.screenshot({fullPage:config.artifacts.fullPageScreenshot});await attach('sdetflow-failure.png',{body:bytes,contentType:'image/png'});screenshotAttached=true}catch(e){warnings.push(`screenshot attachment failed: ${err(e)??'unknown error'}`)}if(config.artifacts.includeDom&&context.dom&&attach)try{await attach('sdetflow-dom.html',{body:context.dom,contentType:'text/html'});domAttached=true}catch(e){warnings.push(`DOM attachment failed: ${err(e)??'unknown error'}`)}return{context,metadataAttached,screenshotAttached,domAttached,warnings}}
