package io.sdetflow.api;

import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import java.util.function.Supplier;

/** Production-oriented dependency-free HTTP testing client built on java.net.http. */
public final class SdetFlowApiClient {
    private final URI baseUri; private final HttpClient http; private final AuthStrategy auth; private final RetryPolicy retry; private final Duration requestTimeout; private final Consumer<RequestEvent> events; private final Map<String,String> defaultHeaders; private final Supplier<String> correlationIdSupplier;
    private SdetFlowApiClient(Builder b){baseUri=b.baseUri;http=b.http!=null?b.http:HttpClient.newBuilder().connectTimeout(b.connectTimeout).followRedirects(HttpClient.Redirect.NORMAL).build();auth=b.auth;retry=b.retry;requestTimeout=b.requestTimeout;events=b.events;defaultHeaders=Map.copyOf(b.defaultHeaders);correlationIdSupplier=b.correlationIdSupplier;}
    public static Builder builder(String baseUri){return new Builder(baseUri);} public ApiRequest get(String p){return new ApiRequest("GET",p);} public ApiRequest post(String p){return new ApiRequest("POST",p);} public ApiRequest put(String p){return new ApiRequest("PUT",p);} public ApiRequest patch(String p){return new ApiRequest("PATCH",p);} public ApiRequest delete(String p){return new ApiRequest("DELETE",p);}
    public ApiResponse execute(ApiRequest request)throws IOException,InterruptedException{Objects.requireNonNull(request,"request");Exception last=null;int max=request.idempotent?retry.maxAttempts():1;for(int attempt=1;attempt<=max;attempt++){long started=System.nanoTime();try{HttpRequest hr=toHttpRequest(request);emit(new RequestEvent("attempt",request.method,Redactor.redact(hr.uri().toString()),attempt,null,null,null));HttpResponse<String> r=http.send(hr,HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));long dur=(System.nanoTime()-started)/1_000_000;emit(new RequestEvent("response",request.method,Redactor.redact(hr.uri().toString()),attempt,r.statusCode(),dur,null));if(request.idempotent&&attempt<max&&retryableStatus(r.statusCode())){sleep(delayForResponse(r,attempt));continue;}return new ApiResponse(r.statusCode(),r.headers(),r.body(),dur);}catch(IOException ex){last=ex;emit(new RequestEvent("transport-error",request.method,Redactor.redact(resolveUri(request).toString()),attempt,null,null,Redactor.redact(ex.getMessage())));if(!request.idempotent||attempt>=max)throw ex;sleep(retry.delayForAttempt(attempt));}}if(last instanceof IOException io)throw io;throw new IOException("Request failed");}
    private long delayForResponse(HttpResponse<?> r,int attempt){var h=r.headers().firstValue("Retry-After").orElse(null);if(h!=null)try{return Math.min(retry.maxDelayMs(),Long.parseLong(h.trim())*1000L);}catch(NumberFormatException ignored){}return retry.delayForAttempt(attempt);}
    private HttpRequest toHttpRequest(ApiRequest r){URI uri=resolveUri(r);HttpRequest.Builder b=HttpRequest.newBuilder().timeout(requestTimeout);defaultHeaders.forEach(b::header);r.headers.forEach(b::header);if(correlationIdSupplier!=null&&!r.headers.containsKey("X-Correlation-Id")){String id=correlationIdSupplier.get();if(id!=null&&!id.isBlank())b.header("X-Correlation-Id",id);}uri=auth.apply(b,uri);b.uri(uri);HttpRequest.BodyPublisher body=r.body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(r.body,StandardCharsets.UTF_8);b.method(r.method,body);return b.build();}
    private URI resolveUri(ApiRequest r){URI uri=baseUri.resolve(r.path.startsWith("/")?r.path.substring(1):r.path);if(r.query.isEmpty())return uri;StringBuilder q=new StringBuilder(uri.getQuery()==null?"":uri.getQuery());for(var e:r.query.entrySet()){if(!q.isEmpty())q.append('&');q.append(urlEncode(e.getKey())).append('=').append(urlEncode(e.getValue()));}try{return new URI(uri.getScheme(),uri.getAuthority(),uri.getPath(),q.toString(),uri.getFragment());}catch(Exception e){throw new IllegalArgumentException("Unable to build request URI",e);}}
    static String urlEncode(String v){return URLEncoder.encode(v,StandardCharsets.UTF_8);} private static boolean retryableStatus(int s){return s==408||s==425||s==429||s>=500;} private static void sleep(long ms)throws InterruptedException{if(ms>0)Thread.sleep(ms);} private void emit(RequestEvent e){if(events!=null)try{events.accept(e);}catch(RuntimeException ignored){}}
    public static final class Builder { private final URI baseUri; private HttpClient http; private AuthStrategy auth=AuthStrategy.none(); private RetryPolicy retry=RetryPolicy.defaults(); private Duration connectTimeout=Duration.ofSeconds(5),requestTimeout=Duration.ofSeconds(30); private Consumer<RequestEvent> events; private final Map<String,String> defaultHeaders=new LinkedHashMap<>(); private Supplier<String> correlationIdSupplier;
      private Builder(String u){if(u==null||u.isBlank())throw new IllegalArgumentException("baseUri is required");URI p=URI.create(u.endsWith("/")?u:u+"/");if(p.getScheme()==null||p.getHost()==null)throw new IllegalArgumentException("baseUri must be absolute HTTP(S) URI");if(!p.getScheme().equals("http")&&!p.getScheme().equals("https"))throw new IllegalArgumentException("baseUri scheme must be http or https");baseUri=p;defaultHeaders.put("Accept","application/json");defaultHeaders.put("User-Agent","sdetflow-api/0.2.0");}
      public Builder httpClient(HttpClient v){http=v;return this;} public Builder auth(AuthStrategy v){auth=Objects.requireNonNull(v);return this;} public Builder retryPolicy(RetryPolicy v){retry=Objects.requireNonNull(v);return this;} public Builder connectTimeout(Duration v){connectTimeout=positive(v,"connectTimeout");return this;} public Builder requestTimeout(Duration v){requestTimeout=positive(v,"requestTimeout");return this;} public Builder onEvent(Consumer<RequestEvent> v){events=v;return this;} public Builder defaultHeader(String n,String v){if(n==null||n.isBlank())throw new IllegalArgumentException("header name required");defaultHeaders.put(n,v);return this;} public Builder correlationIdSupplier(Supplier<String> v){correlationIdSupplier=v;return this;} public SdetFlowApiClient build(){return new SdetFlowApiClient(this);} private static Duration positive(Duration v,String n){Objects.requireNonNull(v);if(v.isZero()||v.isNegative())throw new IllegalArgumentException(n+" must be positive");return v;}
    }
}
